foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path


handler404 = 'recipes.views.page_not_found'
handler500 = 'recipes.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('recipes.urls')),
    path(
        'about-project/', views.flatpage,
        {'url': '/about-project/'}, name='about-project'),
    path(
        'about-author/', views.flatpage,
        {'url': '/about-author/'}, name='about-author'),
    path(
        'about-spec/', views.flatpage,
        {'url': '/about-spec/'}, name='about-spec'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('subscriptions/', views.follow_index, name='subscriptions'),
    path('subscriptions/subscribe/', views.profile_follow, name='subscriptions_subscribe'),
    path('unsubscribe/<int:author_id>/', views.profile_unsubscribe, name='subscriptions_unsubscribe'),
    path('favorit/', views.favorit_index, name='favorit'),
    path('favorit/add/', views.favorite_add, name='favorit_add'),
    path('favorit/<int:recipe_id>/remove/', views.favorite_remove, name='favorit_remove'),
    path('recipe/<int:recipe_id>/', views.recipe_view, name='recipe'),
    path('recipe/new/', views.recipe_new, name='recipe_new'),
    path(
        'recipe/<int:recipe_id>/edit/',
        views.recipe_edit,
        name='recipe_edit'
    ),
    path(
        'recipe/<int:recipe_id>/delete/',
        views.recipe_delete,
        name='recipe_delete'
    ),
    path('ingredients/', views.ingredients, name='ingredients'),
    path('cart/', views.cart_list, name='cart'),
    path(
        'cart/download/',
        views.cart_list_download,
        name='cart_download'
    ),
    path(
        'cart/<int:recipe_id>/remove/',
        views.cart_remove,
        name='cart_remove'
    ),
    path(
        'cart/<int:recipe_id>/delete/',
        views.cart_delete_recipe,
        name='cart_delete'
    ),
    path('cart/add/', views.cart_add, name='cart_add'),

    path('profile/<str:username>/', views.profile, name='profile'),
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    TAG_CHOICES = [
        ('breakfast', 'завтрак'),
        ('lunch', 'обед'),
        ('dinner', 'ужин'),
    ]
    title = models.CharField(
        max_length=50,
        choices=TAG_CHOICES
    )

    def __str__(self):
        return self.title


class Ingredient(models.Model):

    title = models.CharField(
        max_length=300
    )
    dimension = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )

    def __str__(self):
        return str(self.title)


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes'
    )
    title = models.CharField(max_length=300)
    description = models.TextField()
    ingredient = models.ManyToManyField(
        Ingredient,
        through='RecipeIngredient',
        through_fields=('recipe', 'ingredient'),
        related_name='ingredients'
    )
    cooking_time = models.PositiveSmallIntegerField()
    pub_date = models.DateTimeField(
        auto_now_add=True
    )
    tag = models.ManyToManyField(
        Tag, related_name='tags'
    )
    image = models.ImageField(
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-pub_date']

    def get_ingredients(self):
        return self.ingredient.all().values_list('title', flat=True)

    def get_tags(self):
        return self.tag.all().values_list('title', flat=True)


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='quantities'
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name='recipe_quantity'
    )
    quantity = models.FloatField()

    def __str__(self):
        return str(self.ingredient)


class Cart(models.Model):
    shopper = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='carts'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='recipe_carts'
    )

    def __str__(self):
        return self.recipe.title

    class Meta:
        unique_together = ('shopper', 'recipe')


class Favorit(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_favorits'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='favorits'
    )

    def __str__(self):
        return f'author - {self.author} | recipe - {self.recipe.title}'

    class Meta:
        unique_together = ('author', 'recipe')


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return f'follower - {self.user} | following - {self.author}'

    class Meta:
        unique_together = ('user', 'author')

recipes/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'tag', 'cooking_time', 'description', 'image')
        widgets = {
            'tag': forms.CheckboxSelectMultiple(),
        }

recipes/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from foodgram.settings import paginator_items_on_page as items_on_page

from .forms import RecipeForm
from .models import (Cart, Favorit, Follow, Ingredient, Recipe,
                     RecipeIngredient, User)
from .service import create_recipe_ingredient, get_ingredients, get_tags


def page_not_found(request, exception):
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'misc/500.html', status=500)


def index(request):
    recipes = Recipe.objects.select_related(
        'author').prefetch_related('tag',)

    tags_qs = get_tags(request)
    if tags_qs:
        recipes = Recipe.objects.filter(tag__in=tags_qs).distinct()

    paginator = Paginator(recipes, items_on_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {
        'page': page,
        'paginator': paginator,
        'recipe': recipes
    })


def profile(request, username):
    account = get_object_or_404(User, username=username)
    account_recipes = account.recipes.all()

    tags_qs = get_tags(request)
    if tags_qs:
        account_recipes = Recipe.objects.filter(
            author=account, tag__in=tags_qs).distinct()

    paginator = Paginator(account_recipes, items_on_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html', {
        'page': page,
        'paginator': paginator,
        'profile': account,
        'recipe': account_recipes
    })


def recipe_view(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    return render(request, 'includes/recipe.html', {
        'recipe': recipe
    })


@login_required
def recipe_new(request):
    author = get_object_or_404(User, username=request.user)

    recipe_form = RecipeForm(
        request.POST or None, files=request.FILES or None
    )

    ingredients_list = get_ingredients(request.POST)

    if recipe_form.is_valid():
        if len(ingredients_list) == 0:
            recipe_form.add_error('title', 'Добавьте хотя бы 1 ингредиент')
            return render(request, 'recipe_form.html', {'form': recipe_form, })
        if [x for x in ingredients_list.values() if float(x) <= 0]:
            recipe_form.add_error('title', 'Количество ингредиентов не '
                                           'может быть равно 0 или меньше')
            return render(request, 'recipe_form.html', {'form': recipe_form, })
        recipe = recipe_form.save(commit=False)
        recipe.author = author
        recipe.save()
        create_recipe_ingredient(ingredients_list, recipe)
        recipe_form.save_m2m()
        return redirect('index')
    return render(request, 'recipe_form.html', {'form': recipe_form, })


@login_required
def recipe_edit(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.user != recipe.author:
        return redirect('recipe', recipe_id=recipe.id)

    ingredients_in_recipe = RecipeIngredient.objects.filter(
        recipe=recipe).select_related('ingredient').all()
    ingredients_list_old = []

    for item in ingredients_in_recipe:
        ingredient_item = []
        ingredient_item.append(item.ingredient.title)
        ingredient_item.append(item.quantity)
        ingredient_item.append(item.ingredient.dimension)
        ingredients_list_old.append(tuple(ingredient_item))

    recipe_form = RecipeForm(
        request.POST or None, files=request.FILES or None, instance=recipe)

    ingredients_list = get_ingredients(request.POST)
    if recipe_form.is_valid():
        if len(ingredients_list) == 0:
            recipe_form.add_error('title', 'Добавьте хотя бы 1 ингредиент')
            return render(request, 'recipe_form.html', {'form': recipe_form, })
        if [x for x in ingredients_list.values() if float(x) <= 0]:
            recipe_form.add_error('title', 'Количество ингредиентов не '
                                           'может быть равно 0 или меньше')
            return render(request, 'recipe_form.html', {'form': recipe_form, })
        recipe = recipe_form.save(commit=False)
        recipe.author = request.user
        recipe.save()
        recipe.quantities.all().delete()
        create_recipe_ingredient(ingredients_list, recipe)
        recipe_form.save_m2m()
        return redirect('index')
    return render(request, 'recipe_change_form.html', {
        'form': recipe_form,
        'recipe': recipe,
        'ingredients_list_old': ingredients_list_old
    })


@login_required
def recipe_delete(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if request.user == recipe.author:
        recipe.delete()
    return redirect('index')


def ingredients(request):
    ingredient = request.GET['query']
    ingredient_list = list(Ingredient.objects.filter(
        title__icontains=ingredient).values('title', 'dimension'))
    return JsonResponse(ingredient_list, safe=False)


@login_required
def cart_add(request):
    recipe_id = json.loads(request.body)['id']
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if Cart.objects.get_or_create(
            shopper=request.user, recipe=recipe):
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


@login_required
def cart_remove(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)

    user = get_object_or_404(User, username=request.user.username)

    obj = get_object_or_404(Cart, shopper=user, recipe=recipe)
    if obj.delete():
        return JsonResponse({'success': False})
    return JsonResponse({'success': True})


@login_required
def cart_list(request):
    recipes = request.user.carts.all()
    return render(request, 'cart_list.html', {'recipes': recipes})


@login_required
def cart_delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Cart, shopper=request.user, recipe=recipe_id)
    recipe.delete()
    return redirect('cart')


@login_required
def cart_list_download(request):
    recipes = Recipe.objects.filter(recipe_carts__shopper=request.user).values(
        'ingredient__title', 'ingredient__dimension', )

    ingredients_list = recipes.annotate(
        quantity=Sum('quantities__quantity')
    ).order_by()

    ingredient_txt = [
        (f"\u2022 {item['ingredient__title'].capitalize()} "
         f"({item['ingredient__dimension']}) \u2014 {item['quantity']} \n")
        for item in ingredients_list
    ]
    file = 'ingredients.txt'
    response = HttpResponse(ingredient_txt, content_type='text/plain')
    response['Content-Disposition'] = f'attachment; filename={file}'
    return response


@login_required
def follow_index(request):
    follows = Follow.objects.select_related(
        'user', 'author'
    ).filter(user=request.user)

    paginator = Paginator(follows, items_on_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'follow.html', {
        'page': page,
        'paginator': paginator,
    })


@login_required
def profile_follow(request):
    author_id = json.loads(request.body)['id']
    author = get_object_or_404(User, id=author_id)

    if request.user == author:
        return JsonResponse({'success': False})

    if not Follow.objects.filter(
            user=request.user, author=author
    ).exists():
        follow = Follow(user=request.user, author=author)
        follow.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


@login_required
def profile_unsubscribe(request, author_id):
    author = get_object_or_404(User, id=author_id)
    if Follow.objects.filter(user=request.user, author=author).delete():
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


@login_required
def favorit_index(request):
    favorit_recipes = Recipe.objects.select_related(
        'author'
    ).prefetch_related('tag',).filter(favorits__author=request.user)

    tags_qs = get_tags(request)
    if tags_qs:
        favorit_recipes = Recipe.objects.filter(
            favorits__author=request.user, tag__in=tags_qs
        ).distinct()

    paginator = Paginator(favorit_recipes, items_on_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'favorit.html', {
        'page': page,
        'paginator': paginator,
        'recipe': favorit_recipes
    })


@login_required
def favorite_add(request):
    recipe_id = json.loads(request.body)['id']
    recipe = get_object_or_404(Recipe, id=recipe_id)

    if Favorit.objects.get_or_create(author=request.user, recipe=recipe):
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})


@login_required
def favorite_remove(request, recipe_id):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    author = get_object_or_404(User, username=request.user.username)
    favorit = get_object_or_404(Favorit, author=author, recipe=recipe)
    if favorit.delete():
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Foodgram{% endblock %}</title>
    {% load static %}
    {% csrf_token %}
</head>
<body class="body">
    {% include 'includes/header.html' %}
    <main class="main container">
        {% block content %}
        {% endblock %}
      </main> 
    {% include 'includes/footer.html' %}
    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/cart_list.html
{% extends 'base.html' %}
{% block title %} Список покупок {% endblock %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with cart_list=True recipe=recipe%}
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
<div class="main__header">
<h1 class="main__title">Список покупок</h1>
</div>
    <div class="card-list card-list_column">
      <ul class="shopping-list">
        {% for recipe in recipes %}
          <li class="shopping-list__item" data-id="{{ recipe.recipe.id }}">
            <div class="recipe recipe_reverse">
              <img src="{{ recipe.recipe.image.url }}" alt="{{ recipe.recipe.title }}" class="recipe__image recipe__image_big">
              <h3 class="recipe__title"><a style="funfollowcolor: #000" href="{% url 'recipe' recipe.recipe.id %}">{{ recipe.recipe.title }}</a></h3>
              <p class="recipe__text"><span class="icon-time"></span> {{ recipe.recipe.cooking_time }} мин.</p>
            </div>
            <a href="{% url 'cart_delete' recipe.recipe.id %}" class="shopping-list__button link">Удалить</a>
          </li>
        {% endfor %}
      </ul>
      {% if recipes %}
        <a class="button button_style_blue" href="{% url 'cart_download' %}">Скачать список</a>
      {% endif %}
    </div>
{% endblock %}

templates/cart_to_pdf.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <title>Foodgram</title>
    <style type="text/css">
        @font-face { font-family: arial; src: url('./static/fonts/arial.ttf'); }
        div { font-family: arial; color: #333333; }
    </style>
</head>
<body>
    
    <main>
        <div>
            <h3 align="center">Foodgram</h3>
            <hr align="center" width="600" size="1" color="#000" />
        </div>
        <p></p>
        <div>
            <h1 align="center">Cart List</h1>
        </div>
        <hr align="center" width="500" size="1" color="#f00" />
        <div>
            <ul>
            {% for ingredient in ingredients %}
                <li>
                <div>
                    <h2>{{ ingredient.ingredient__title }} - {{ ingredient.quantities__quantity__sum }} {{ ingredient.ingredient__dimension }}</h2>
                </div>
                </li>
            {% endfor %}
            </ul>
            <hr align="center" width="500" size="2" color="#ff0000" />
            <h2 align="center">Foodgram</h2>
        </div>
    </main> 

</body>
</html>

templates/favorit.html
{% extends 'base.html' %}
{% block title %} Избранные рецепты {% endblock %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with favorit=True %}
{% endblock %}
{% block content %}
{% load recipe_filters %}
    {% csrf_token %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}"> 
    <div class="main__header">
        <h1 class="main__title">Избранное</h1>
        {% include 'includes/tags.html' %}
    </div>
    <div class="card-list">
        {% for recipe in page %}
            {% include 'includes/recipe_small.html' with recipe=recipe %}
        {% endfor %}
    </div>
        {% if page.has_other_pages %}
            {% include 'includes/paginator.html' with items=page paginator=paginator tags=request|get_tags %}
        {% endif %}
    {% block script %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>
        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/CardList.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>
        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/favorite.js' %}"></script>
    {% endblock %}
{% endblock %}

templates/follow.html
{% extends "base.html" %} 
{% block title %} Мои подписки {% endblock %}
{% block head %}
    {% include 'includes/head.html' with follow=True%}
{% endblock head %}
{% load static %}
{% block content %}
{% load recipe_filters %}
{% csrf_token %}
<link rel="stylesheet" href="/static/pages/myFollow.css">
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
        {% include 'includes/follow_card.html'%}
    </div>
    {% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% include 'includes/paginator.html' with items=page paginator=paginator tags=request|get_tags %}
    </ul>
    {% endif %}
        
    {% block scripts %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/myFollow.js' %}"></script>

    {% endblock %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %} Foodgram {% endblock title %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with index=True%}
{% endblock head %}
{% block content %}
{% load recipe_filters %}
{% csrf_token %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            {% include 'includes/tags.html' %}
        </div>    
        <div class="card-list">
                {% for recipe in page %}
                   {% include 'includes/recipe_small.html' with recipe=recipe %}
                {% endfor %}
       </div>
    {% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% include 'includes/paginator.html' with items=page paginator=paginator tags=request|get_tags %}
    </ul>
    {% endif %}

    {% block scripts %}
            <script src="{% static 'js/config/config.js' %}"></script>
            <script src="{% static 'js/components/MainCards.js' %}"></script>
            <script src="{% static 'js/components/Purchases.js' %}"></script>
            <script src="{% static 'js/components/CardList.js' %}"></script>
            <script src="{% static 'js/components/Header.js' %}"></script>
            <script src="{% static 'js/api/Api.js' %}"></script>
        {% if user.is_authenticated %}
            <script src="{% static 'js/components/Favorites.js' %}"></script>
            <script src="{% static 'js/indexAuth.js' %}"></script>
        {% else %}
            <script src="{% static 'js/indexNotAuth.js' %}"></script>
        {% endif %}
    {% endblock scripts %}
{% endblock %}

templates/profile.html
{% extends "base.html" %} 
{% block title %} Автор рецептов: {{ profile.get_full_name }} {% endblock %}
{% block head %}
    {% include 'includes/head.html'%}
{% endblock %}
{% load static %}
{% load recipe_filters %}
{% block content %}
{% load recipe_filters %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
        <div class="main__header">
            <h1 class="main__title">{{ profile.get_full_name }}</h1>
            {% include 'includes/tags.html' %}
        </div>
        {% csrf_token %}
        {% if user != profile and user.is_authenticated %}
            {% if profile|in_follow:user %}
                <div class="author-subscribe" data-author="{{ profile.id }}">
                    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto" name="subscribe"><span class="icon-check button__icon"></span>Отписаться от автора </button></p>
                </div>
            {% else %}
                <div class="author-subscribe" data-author="{{ profile.id }}">
                    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></p>
                </div>
            {% endif %}
        {% endif %}
        <div class="card-list">
               {% for recipe in page %}
                    {% include 'includes/recipe_small.html' %}
                {% endfor %}
        </div>

    {% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% include 'includes/paginator.html' with items=page paginator=paginator tags=request|get_tags %}
    </ul>

    {% endif %}
        
    {% block scripts %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/authorRecipe.js' %}"></script>

    {% endblock scripts %}

{% endblock %}

templates/recipe_form.html
{% extends "base.html" %} 
{% block title %} Создание рецепта {% endblock %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with new_recipe=True%}
{% endblock %}
{% block content %}
{% load user_filters %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    {% if form.errors %}
                    {% for error in form.title.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="tag" value ="1" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange">
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tag" value ="2" id="id_lunch" class="tags__checkbox tags__checkbox_style_green">
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tag" value ="3" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple">
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    {% if form.errors %}
                    <span class="form__error">Добавьте хотя бы 1 тэг</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0" value="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container"></div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
               </div>
            </div>
           <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time|addclass:"form__input" }}
                    <label for="id_time" class="form__label">минут</label>
                    {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description|addclass:"form__textarea" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {{ form.image|addclass:"form__file-button" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>
    {% block scripts %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/formRecipe.js' %}"></script>
    {% endblock %}
{% endblock %}